/**
 * Presets — named parameter snapshots for the synth.
 *
 * Each preset contains a complete set of all audio parameters so that
 * loading one replaces the entire patch without partial state.
 */

export const PRESETS = [
  {
    id: 'init',
    name: 'Init',
    description: 'Default patch — clean slate',
    params: {
      waveform: 'sawtooth',
      frequency: 440,
      amplitude: 0.7,
      filterType: 'lowpass',
      filterCutoff: 5000,
      filterResonance: 0.2,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.7,
      release: 0.5,
      lfoWaveform: 'sine',
      lfoRate: 2,
      lfoDepth: 0,
      lfoTarget: 'filter',
      reverbMix: 0,
      reverbDecay: 2,
      delayMix: 0,
      delayTime: 0.3,
      delayFeedback: 0.4,
    },
  },
  {
    id: 'wobble',
    name: 'Wobble',
    description: 'Slow LFO sweeping the filter',
    params: {
      waveform: 'sawtooth',
      frequency: 220,
      amplitude: 0.75,
      filterType: 'lowpass',
      filterCutoff: 2000,
      filterResonance: 0.4,
      attack: 0.01,
      decay: 0.3,
      sustain: 0.8,
      release: 0.5,
      lfoWaveform: 'sine',
      lfoRate: 0.5,
      lfoDepth: 0.8,
      lfoTarget: 'filter',
      reverbMix: 0.15,
      reverbDecay: 2,
      delayMix: 0,
      delayTime: 0.3,
      delayFeedback: 0.4,
    },
  },
  {
    id: 'acid',
    name: 'Acid',
    description: 'Squelchy TB-303 vibe',
    params: {
      waveform: 'square',
      frequency: 110,
      amplitude: 0.8,
      filterType: 'lowpass',
      filterCutoff: 800,
      filterResonance: 0.85,
      attack: 0.005,
      decay: 0.2,
      sustain: 0.3,
      release: 0.1,
      lfoWaveform: 'sine',
      lfoRate: 2,
      lfoDepth: 0,
      lfoTarget: 'filter',
      reverbMix: 0.05,
      reverbDecay: 1,
      delayMix: 0.1,
      delayTime: 0.15,
      delayFeedback: 0.3,
    },
  },
  {
    id: 'pad',
    name: 'Pad',
    description: 'Slow, spacious ambient chords',
    params: {
      waveform: 'sine',
      frequency: 220,
      amplitude: 0.65,
      filterType: 'lowpass',
      filterCutoff: 1800,
      filterResonance: 0.1,
      attack: 1.2,
      decay: 0.5,
      sustain: 0.9,
      release: 2.0,
      lfoWaveform: 'sine',
      lfoRate: 0.3,
      lfoDepth: 0.15,
      lfoTarget: 'amplitude',
      reverbMix: 0.6,
      reverbDecay: 4,
      delayMix: 0.2,
      delayTime: 0.5,
      delayFeedback: 0.4,
    },
  },
  {
    id: 'lead',
    name: 'Lead',
    description: 'Bright synth lead with echo',
    params: {
      waveform: 'sawtooth',
      frequency: 440,
      amplitude: 0.7,
      filterType: 'lowpass',
      filterCutoff: 3000,
      filterResonance: 0.35,
      attack: 0.01,
      decay: 0.15,
      sustain: 0.6,
      release: 0.4,
      lfoWaveform: 'sine',
      lfoRate: 5,
      lfoDepth: 0.1,
      lfoTarget: 'pitch',
      reverbMix: 0.1,
      reverbDecay: 1.5,
      delayMix: 0.35,
      delayTime: 0.3,
      delayFeedback: 0.45,
    },
  },
  {
    id: 'bass',
    name: 'Bass',
    description: 'Deep sub bass, tight and punchy',
    params: {
      waveform: 'sine',
      frequency: 110,
      amplitude: 0.85,
      filterType: 'lowpass',
      filterCutoff: 400,
      filterResonance: 0.15,
      attack: 0.005,
      decay: 0.1,
      sustain: 0.7,
      release: 0.2,
      lfoWaveform: 'sine',
      lfoRate: 2,
      lfoDepth: 0,
      lfoTarget: 'filter',
      reverbMix: 0,
      reverbDecay: 1,
      delayMix: 0,
      delayTime: 0.3,
      delayFeedback: 0.2,
    },
  },
  {
    id: 'pluck',
    name: 'Pluck',
    description: 'Percussive string-like pluck',
    params: {
      waveform: 'sawtooth',
      frequency: 440,
      amplitude: 0.75,
      filterType: 'lowpass',
      filterCutoff: 4000,
      filterResonance: 0.25,
      attack: 0.005,
      decay: 0.15,
      sustain: 0.1,
      release: 0.3,
      lfoWaveform: 'sine',
      lfoRate: 2,
      lfoDepth: 0,
      lfoTarget: 'filter',
      reverbMix: 0.25,
      reverbDecay: 1.5,
      delayMix: 0.15,
      delayTime: 0.25,
      delayFeedback: 0.35,
    },
  },
]
